// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqqnbpgoqtnrzjgzllja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcW5icGdvcXRucnpqZ3psbGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDg4NTQsImV4cCI6MjA1OTU4NDg1NH0.7pNJ3hmrED_BM1qB9Z-_KNYPdjAnnRm4cpQYWeEXlTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);